// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "greet", input: string, result: string },
    subscriptions: 
        { key: "test_event", input: never, result: string }
};
